version: '3.8'

services:
  backend:
    build: ../apps/backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:pass@db:5432/community
    depends_on:
      - db

  frontend:
    build: ../apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: abboskhonov
      POSTGRES_PASSWORD: abror2520
      POSTGRES_DB: discord
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
